// get EMPLOYEE request

export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEES_FAILURE = "GET_EMPLOYEE_FAILURE";

//  POST REQUEST
export const POST_EMPLOYEE_REQUEST = "POST_EMPLOYEE_REQUEST";
export const POST_EMPLOYEE_SUCCESS = "POST_EMPLOYEE_SUCCESS";
export const POST_EMPLOYEE_FAILURE = "POST_EMPLOYEE_FAILURE";

//  PUT REQUEST
export const PUT_EMPLOYEE_REQUEST = "PUT_EMPLOYEE_REQUEST";
export const PUT_EMPLOYEE_SUCCESS = "PUT_EMPLOYEE_SUCCESS";
export const PUT_EMPLOYEE_FAILURE = "PUT_EMPLOYEE_FAILURE";

//  DELETE REQUEST
export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE";